server:
  port: 8082
spring:
  application:
    name:
      fmtok8s-api-gateway-service
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
        - RemoveRequestHeader=Cookie
      httpclient:
        wiretap: true
      httpserver:
          wiretap: true
      routes:
      - id: agenda
        uri: ${AGENDA_SERVICE:http://fmtok8s-agenda}
        predicates:
          - Path=/agenda/**
        filters:
          - RewritePath=/agenda/(?<id>.*), /$\{id}
          - name: CircuitBreaker
            args:
              name: agendaCircuitBreaker
              fallbackUri: forward:/api/agendaNotAvailable
      - id: c4p
        uri: ${C4P_SERVICE:http://fmtok8s-c4p}
        predicates:
        - Path=/c4p/**
        filters:
          - RewritePath=/c4p/(?<id>.*), /$\{id}
          - name: CircuitBreaker
            args:
              name: c4pCircuitBreaker
              fallbackUri: forward:/api/c4pNotAvailable
      - id: email
        uri: ${EMAIL_SERVICE:http://fmtok8s-email}
        predicates:
        - Path=/email/**
        filters:
          - RewritePath=/email/(?<id>.*), /$\{id}
          - name: CircuitBreaker
            args:
              name: c4pCircuitBreaker
              fallbackUri: forward:/api/emailNotAvailable
      - id: speakers
        uri: ${SPEAKERS_SERVICE:http://fmtok8s-speakers}
        predicates:
          - Path=/speakers/**
        filters:
          - RewritePath=/speakers/(?<id>.*), /$\{id}
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: http://localhost:8080/auth/realms/fmtok8s
        registration:
          oidc:
            client-name: keycloak
            provider: oidc
            client-id: gateway
            client-secret: 7208a758-e57c-4045-8c4a-9831bb2b8144


management:
  endpoints:
    web:
      exposure:
        include: health, gateway, info, prometheus, metrics, threaddump
  endpoint:
    loggers:
      enabled: true
    info:
      enabled: true
      show-details: always
    gateway:
      enabled: true
      show-details: always
    health:
      probes:
        enabled: true
      enabled: true
      show-details: always
      group:
        liveness:
          include: livenessState
          show-details: always
        readiness:
          include: readinessState
          show-details: always

logging:
  level:
    reactor:
      netty: TRACE
    org:
      springframework:
        cloud:
          gateway: TRACE